### PR TITLE
IR sensor as remote shutter

### PR DESCRIPTION
**Pull request by partlyhuman**
Hey Toxa! Apologies in advance, this is my first stab at GBDK. I've been chasing the dream of a remote shutter for GB Camera for a while -- I like to take GB Cameras to events and do a kind of a selfie booth. In the past I modded a DMG with a physical shutter jacking into the A button, and then much later put an IR sensor in a DMG using a microcontroller to simulate button presses. But it dawned on me that now we can build it right into the software if you have a GBC!

This actually works(!!!), the one issue being that the IR sensor is inconveniently pointed up. However, I found some 9mm prisms on aliexpress for a few bucks and when they arrive I think it will be a trivial and possibly reversible modification for anyone who wants the selfie-remote experience.

Rather than actually detecting the pattern of any IR remote, here I'm just recognizing any rapid flashing as a remote -- I can disguise my laziness here with the fact that we really want to recognize all manner of remotes indiscriminately.

Feel free to close this PR and take it in your own direction (or not), but thank you for making Photo! open source so I can at least have this feature that's been a dream for years! :)

### CODE REVIEW

**Comment by untoxa** [comment]
this slows down the display refresh rate and also not work at daylight on street. so, i suggest:
1. add setting (off by default), that enables this feature; see: https://github.com/untoxa/gb-photo/commit/06943916feb78d129b3811f76197e96263364d60
2. make ir_sense_start()/ir_sense_stop() inline, move them into the header
3. SENSE_DUR should be a define, SDCC can't eliminate the use of the real variable here
4. yes, you can't use CPU speed switching, not only because of the visual glitches, but also because of the GB Camera hardware

**Comment by partlyhuman** [comment]
Thanks! I'll implement these :)

**Comment by untoxa** [comment]
well, but now you have a setting, that switches between "A", "timer", "repeat" and "IR". but, actually, when you select IR, it works as "EITER A OR IR". your first approach in https://github.com/untoxa/gb-photo/pull/30/commits/3278ba3deb08c5c40ed4a3d93dad7802209944a2 looks better to me.

**Comment by partlyhuman** [comment]
> well, but now you have a setting, that switches between "A", "timer", "repeat" and "IR". but, actually, when you select IR, it works as "EITER A OR IR". your first approach in [3278ba3](https://github.com/untoxa/gb-photo/commit/3278ba3deb08c5c40ed4a3d93dad7802209944a2) looks better to me.

Yeah, the more I thought about it the more IR seemed to be a trigger mode: it's a way to trigger the shutter, and I don't want it in combination with countdown or repeat modes ever, I would want to use it to take a single shot immediately, so it also makes sense to me to be a mutually exclusive trigger method.

The fact that "A" still fires the shutter seemed desirable, in case someone picks up the camera they're not prevented from using the manual shutter. Further, this goes along with all the other trigger modes that use "A" as the shutter. But this is certainly an easy fix if you think it's confusing.

Ultimately it's up to you where this feature goes if anywhere, but after giving it some thought it eventually made more sense as a trigger. I'll keep mulling it over and maybe go back and try it the Settings way again and see how it feels.

**Comment by untoxa** [comment]
i don't see why IR should not be used with repeat or timer mode, when you make selfie using remote and want to hide your hand before camera make the picture.

**Comment by untoxa** [comment]
that also corresponds with the behavior of the link-cable shutter device

**Comment by partlyhuman** [comment]
> also, will be nice to have a game boy rom that sends the IR commands, that may be separate rom or improvement to the "remote": https://github.com/untoxa/gb-photo/blob/master/remote/src/main.c

This is a really interesting idea!

I see your points about making this operate just like it would from the link cable remote... give me a day and I'll move it back into the settings and clean up!

**Comment by partlyhuman** [comment]
Okay, back to being a setting - and we're not treating IR shutter special in any way, it can be combined with any trigger mode and is subject to save confirmation if you turn that on.

Added IR to the remote, and tried to allow hot-plug of the link cable, refreshing the screen graphic to reflect this status, and only blasting IR when the link cable is disconnected -- so IR or link cable is used depending on which is available.

Only IR shutter is implemented now but we could definitely implement a full control scheme. But shutter covers 90% of the use cases I think.

It might be a good idea to add an `.enabled` function pointer to the menu structs so one could conditionally show / not show menu items such as IR, CGB palette, SGB border while continuing to keep the menu data `const`; the height would have to be recalculated based on number of enabled items. Instead of this I've just made IR display a `-` when not available. This could be a disabled checkbox in the icon font, but I think maybe hiding it would be better overall.

Happy to implement any other feedback here, want to get it right.

**Comment by untoxa** [comment]
`uint16_t guard` is useless because there is no flow control. 0x80 bit will stay fixed amount of time, no matter if there is a connected device or not.

**Comment by untoxa** [comment]
about dynamic menus. i don't think it is worth implementing the dynamically allocated menus, will be much simpler and with the same efficiency implement "graying" of the menu items. how that may be implemented:
1. implement graying in the VWF rendering. probably, using a global variable for speed, not function parameter(s). rendering is not too fast to make it even slower, we should be careful.
2. implement a menu item status callback: takes menu id as a parameter and returns bool. null pointer means "enabled".
3. implement navigation, that skips the grayed menu items, rollback when it is not possible to move forward and menu is not looped.
that seem very doable, but that must be separate PR of course.

**Comment by partlyhuman** [comment]
> uint16_t guard is useless because there is no flow control. 0x80 bit will stay fixed amount of time, no matter if there is a connected device or not.

HEhe yeah, I realized that eventually after some testing. Missed that in cleanup!

> probably you forgot to push the updated PNG.

I didn't change the PNG, but I guess you mean it would be cool if the background indicated that the IR is active somehow... I can try to do that? I'm not an artist but I can try :)

Good ideas on the disabled menus :) I thought maybe "greyed out" wouldn't be clear enough with 2 bit color but inverse is a great idea.

OK, so what should I do here? I'll clean up the `guard`... let me know what you had in mind for the "updated PNG"?

**Comment by untoxa** [comment]
ah, it flashes the "game boy screen". i thought it does nothing, because images are identical, they are not at that point.

**Comment by partlyhuman** [comment]
That's right! idea was to have the DMG screen on in the graphic when the link cable is connected and off when it's not.

**Pull request merged**
